# Generated by Django 3.1.2 on 2021-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('aboutme', models.CharField(default='', max_length=10000, verbose_name='Few lines about yourself')),
                ('phoneno', models.IntegerField(default=0)),
                ('emailid', models.EmailField(default='', max_length=100, verbose_name='Email Id')),
                ('profession', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('linkedinlink', models.CharField(blank=True, default='', max_length=2000, verbose_name='Linkedin URL')),
                ('twitterlink', models.CharField(blank=True, default='', max_length=2000, verbose_name='Twitter URL')),
                ('instagramlink', models.CharField(blank=True, default='', max_length=2000, verbose_name='Instagram URL')),
                ('behancelink', models.CharField(blank=True, default='', max_length=2000, verbose_name='Behance URL')),
                ('githublink', models.CharField(blank=True, default='', max_length=2000, verbose_name='Github URL')),
                ('skillstext', models.CharField(default='', max_length=10000, verbose_name='Few lines about your skillset')),
                ('skill1', models.CharField(default='', max_length=100)),
                ('skill1p', models.IntegerField(default=1, verbose_name='Skill 1 percentage')),
                ('skill2', models.CharField(default='', max_length=100)),
                ('skill2p', models.IntegerField(default=1, verbose_name='Skill 2 percentage')),
                ('skill3', models.CharField(default='', max_length=100)),
                ('skill3p', models.IntegerField(default=1, verbose_name='Skill 3 percentage')),
                ('skill4', models.CharField(default='', max_length=100)),
                ('skill4p', models.IntegerField(default=1, verbose_name='Skill 4 percentage')),
                ('project1', models.CharField(default='', max_length=100, verbose_name='Project 1 name')),
                ('work1', models.CharField(default='', max_length=100, verbose_name='Project 1 URL')),
                ('project2', models.CharField(default='', max_length=100, verbose_name='Project 2 name')),
                ('work2', models.CharField(default='', max_length=100, verbose_name='Project 2 URL')),
                ('project3', models.CharField(default='', max_length=100, verbose_name='Project 3 name')),
                ('work3', models.CharField(default='', max_length=100, verbose_name='Project 3 URL')),
                ('project4', models.CharField(blank=True, default='', max_length=100, verbose_name='Project 4 name')),
                ('work4', models.CharField(blank=True, default='', max_length=100, verbose_name='Project 4 URL')),
                ('project5', models.CharField(blank=True, default='', max_length=100, verbose_name='Project 5 name')),
                ('work5', models.CharField(blank=True, default='', max_length=100, verbose_name='Project 5 URL')),
                ('project6', models.CharField(blank=True, default='', max_length=100, verbose_name='Project 6 name')),
                ('work6', models.CharField(blank=True, default='', max_length=100, verbose_name='Project 6 URL')),
                ('photo', models.ImageField(blank=True, default='images/perfil.png', null=True, upload_to='images')),
            ],
        ),
    ]
